/teleop_robot_bridge:
  ros__parameters:
    video:
      fov_table:
        - width: 3840
          height: 1080
          hfov: 99.52
          vfov: 72.21
          dfov: 108.44
        - width: 5120
          height: 1440
          hfov: 99.29
          vfov: 72.08
          dfov: 108.24
        - width: 5184
          height: 1944
          hfov: 98.52
          vfov: 82.14
          dfov: 110.84
